import { useState } from "react";
import { Sparkles, ShieldAlert, Loader2, AlertTriangle, ShieldCheck, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  useAiChat,
  useAnalyzeCircuitSafety,
  useCompileCircuit,
  type LlmAnalyzeResult,
  type Netlist,
} from "@workspace/api-client-react";
import { AiProviderSettings, getProviderLabel, isProviderConfigured, CIRCUIT_GENERATE_SYSTEM_PROMPT } from "@/lib/ai-provider";

interface AiAssistantPanelProps {
  settings: AiProviderSettings;
  onOpenSettings: () => void;
  netlist: Netlist | null | undefined;
  source: string;
  analysisResult: LlmAnalyzeResult | null;
  setAnalysisResult: (r: LlmAnalyzeResult | null) => void;
  onInsertCode: (code: string) => void;
}

export function AiAssistantPanel({
  settings,
  onOpenSettings,
  netlist,
  source,
  analysisResult,
  setAnalysisResult,
  onInsertCode,
}: AiAssistantPanelProps) {
  const [description, setDescription] = useState("");
  const [generatedBy, setGeneratedBy] = useState("");
  const [compileErrors, setCompileErrors] = useState<string[]>([]);
  const [activeTab, setActiveTab] = useState("generate");

  const aiChatMutation = useAiChat();
  const compileMutation = useCompileCircuit();
  const analyzeMutation = useAnalyzeCircuitSafety();

  const configured = isProviderConfigured(settings);

  const handleGenerate = () => {
    if (!description.trim()) return;
    if (!configured) { onOpenSettings(); return; }

    setCompileErrors([]);
    setGeneratedBy("");

    aiChatMutation.mutate(
      {
        data: {
          provider: settings.activeProvider,
          model:
            settings.activeProvider === "cloud"
              ? settings.cloud.model
              : settings.activeProvider === "google"
                ? settings.google.model
                : settings.local.model,
          systemPrompt: CIRCUIT_GENERATE_SYSTEM_PROMPT,
          userMessage: `Generate a circuit for: ${description}`,
          ...(settings.activeProvider === "cloud" ? { apiKey: settings.cloud.apiKey } : {}),
          ...(settings.activeProvider === "google" ? { googleApiKey: settings.google.apiKey } : {}),
          ...(settings.activeProvider === "local" ? { ollamaUrl: settings.local.baseUrl } : {}),
        },
      },
      {
        onSuccess: (aiData) => {
          // Pre-insert validation: compile the AI output before inserting
          compileMutation.mutate(
            { data: { source: aiData.response } },
            {
              onSuccess: (result) => {
                const errs = result.errors?.filter((e) => e.severity === "error") ?? [];
                if (errs.length > 0) {
                  setCompileErrors(errs.map((e) => `L${e.line}: ${e.message}`));
                  setGeneratedBy(`⚠ ${aiData.model} — validation failed (${errs.length} error${errs.length > 1 ? "s" : ""})`);
                } else {
                  onInsertCode(aiData.response);
                  setGeneratedBy(`✓ Generated by ${aiData.model} (${aiData.provider})`);
                  setCompileErrors([]);
                }
              },
              onError: () => {
                // Compile endpoint unreachable — insert anyway
                onInsertCode(aiData.response);
                setGeneratedBy(`✓ Generated by ${aiData.model} (${aiData.provider})`);
              },
            }
          );
        },
      }
    );
  };

  const handleAnalyze = () => {
    setAnalysisResult(null);
    analyzeMutation.mutate(
      { data: { source, netlist: netlist ?? undefined } },
      {
        onSuccess: (result) => {
          setAnalysisResult(result);
          setActiveTab("safety");
        },
      }
    );
  };

  const scoreColor = (score: number) =>
    score >= 90 ? "#3FB950" : score >= 70 ? "#D29922" : score >= 50 ? "#F0883E" : "#F85149";

  const scoreLabel = (score: number) =>
    score >= 90 ? "🟢 Safe" : score >= 70 ? "🟡 Review Recommended" : score >= 50 ? "🟠 Issues Detected" : "🔴 Dangerous";

  return (
    <div className="flex flex-col h-full" style={{ background: "#0D1117" }}>
      <div className="px-4 py-3 border-b flex items-center justify-between shrink-0" style={{ borderColor: "#21262D" }}>
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4" style={{ color: "#58A6FF" }} />
          <span className="text-xs font-mono font-semibold uppercase tracking-wider" style={{ color: "#8B949E" }}>
            AI Circuit Assistant
          </span>
        </div>
        <button
          onClick={onOpenSettings}
          className="flex items-center gap-1.5 px-2 py-1 rounded text-[10px] font-mono hover:bg-[#161B22] transition-colors"
          style={{
            color: configured ? "#3FB950" : "#F0883E",
            border: "1px solid",
            borderColor: configured ? "#2D5A2D" : "#5A2D1A",
          }}
        >
          {configured ? "●" : "○"} {getProviderLabel(settings).slice(0, 24)}
          <ChevronRight className="w-3 h-3" />
        </button>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col min-h-0">
        <TabsList
          className="w-full rounded-none border-b h-9 shrink-0"
          style={{ background: "#0D1117", borderColor: "#21262D" }}
        >
          <TabsTrigger
            value="generate"
            className="flex-1 font-mono text-xs gap-1.5 data-[state=active]:bg-transparent data-[state=active]:border-b-2 data-[state=active]:border-blue-400 rounded-none h-full"
            style={{ color: "#8B949E" }}
          >
            <Sparkles className="w-3 h-3" />
            Generate
          </TabsTrigger>
          <TabsTrigger
            value="safety"
            className="flex-1 font-mono text-xs gap-1.5 data-[state=active]:bg-transparent data-[state=active]:border-b-2 data-[state=active]:border-amber-400 rounded-none h-full"
            style={{ color: "#8B949E" }}
          >
            <ShieldAlert className="w-3 h-3" />
            Safety
          </TabsTrigger>
        </TabsList>

        <TabsContent value="generate" className="flex-1 flex flex-col p-4 gap-4 m-0 overflow-auto">
          {!configured && (
            <div
              className="rounded p-3 text-xs font-mono leading-relaxed"
              style={{ background: "#1F2937", border: "1px solid #30363D", color: "#8B949E" }}
            >
              Configure an AI provider to enable code generation.{" "}
              <button onClick={onOpenSettings} style={{ color: "#58A6FF" }}>
                Open settings →
              </button>
            </div>
          )}

          <div className="space-y-2">
            <label className="text-[10px] font-mono uppercase tracking-wider" style={{ color: "#6E7681" }}>
              Describe your circuit
            </label>
            <textarea
              className="w-full rounded px-3 py-2.5 font-mono text-xs resize-none focus:outline-none focus:ring-1 focus:ring-blue-500 leading-relaxed"
              style={{
                background: "#161B22",
                color: "#C9D1D9",
                border: "1px solid #30363D",
                height: "120px",
              }}
              placeholder="e.g. IR obstacle sensor using 2N2222 transistor, IR LED pair, indicator LED, buzzer, 5V supply"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              onKeyDown={(e) => {
                if ((e.ctrlKey || e.metaKey) && e.key === "Enter") handleGenerate();
              }}
            />
          </div>

          <Button
            onClick={handleGenerate}
            disabled={aiChatMutation.isPending || !description.trim()}
            className="w-full font-mono text-xs h-9 gap-2"
            style={{ background: "#1F6FEB", color: "#fff" }}
          >
            {aiChatMutation.isPending ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Sparkles className="w-3.5 h-3.5" />
            )}
            {aiChatMutation.isPending ? "Generating..." : "⚡ Generate Circuit Code"}
          </Button>

          {aiChatMutation.isPending && (
            <p className="text-xs font-mono animate-pulse text-center" style={{ color: "#8B949E" }}>
              Using {getProviderLabel(settings)}...
            </p>
          )}

          {generatedBy && !aiChatMutation.isPending && (
            <p className="text-[10px] font-mono text-center" style={{ color: "#3FB950" }}>
              {generatedBy}
            </p>
          )}

          {aiChatMutation.isError && (
            <div
              className="rounded p-2.5 text-xs font-mono"
              style={{ background: "#3C1A1A", color: "#F85149", border: "1px solid #5A2D2D" }}
            >
              {(aiChatMutation.error as Error)?.message ?? "Generation failed"}
            </div>
          )}

          {compileErrors.length > 0 && (
            <div
              className="rounded p-3 text-xs font-mono space-y-1"
              style={{ background: "#2D1A1A", border: "1px solid #5A2D2D" }}
            >
              <div className="flex items-center gap-1.5 mb-2" style={{ color: "#F85149" }}>
                <AlertTriangle className="w-3 h-3" />
                <span className="font-semibold">Generated code failed validation — not inserted</span>
              </div>
              {compileErrors.map((err, i) => (
                <div key={i} style={{ color: "#F0883E" }}>{err}</div>
              ))}
              <div className="pt-1" style={{ color: "#8B949E" }}>
                Try adding more detail to your description, or insert manually and fix the errors.
              </div>
            </div>
          )}

          <div className="border-t pt-4" style={{ borderColor: "#21262D" }}>
            <p className="text-[10px] font-mono uppercase tracking-wider mb-2" style={{ color: "#6E7681" }}>
              How it works
            </p>
            <ul className="space-y-1.5 text-[10px] font-mono" style={{ color: "#8B949E" }}>
              <li>1. Describe your circuit in plain English</li>
              <li>2. AI generates valid DSL code</li>
              <li>3. Code is compiled & validated before insert</li>
              <li>4. Clean code is inserted into the editor</li>
            </ul>
          </div>
        </TabsContent>

        <TabsContent value="safety" className="flex-1 flex flex-col m-0 min-h-0 overflow-auto">
          <div className="p-4 border-b shrink-0" style={{ borderColor: "#21262D" }}>
            <Button
              onClick={handleAnalyze}
              disabled={analyzeMutation.isPending || !source.trim()}
              className="w-full font-mono text-xs h-9 gap-2"
              style={{ background: "#88360f", color: "#fff" }}
            >
              {analyzeMutation.isPending ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <ShieldAlert className="w-3.5 h-3.5" />
              )}
              {analyzeMutation.isPending ? "Analyzing..." : "Analyze Safety"}
            </Button>
          </div>

          <div className="flex-1 overflow-auto p-4">
            {analyzeMutation.isPending ? (
              <div className="h-full flex flex-col items-center justify-center gap-4 animate-pulse">
                <Loader2 className="w-8 h-8 animate-spin" style={{ color: "#58A6FF" }} />
                <p className="text-xs font-mono" style={{ color: "#8B949E" }}>
                  Analyzing circuit topology...
                </p>
              </div>
            ) : analysisResult ? (
              <div className="space-y-5 pb-4">
                <div className="flex items-center gap-4">
                  <div className="relative w-20 h-20 shrink-0 flex items-center justify-center">
                    <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
                      <circle cx="50" cy="50" r="45" fill="none" stroke="#21262D" strokeWidth="8" />
                      <circle
                        cx="50"
                        cy="50"
                        r="45"
                        fill="none"
                        stroke={scoreColor(analysisResult.safetyScore)}
                        strokeWidth="8"
                        strokeDasharray="282.7"
                        strokeDashoffset={282.7 - (282.7 * analysisResult.safetyScore) / 100}
                        strokeLinecap="round"
                      />
                    </svg>
                    <div className="absolute inset-0 flex flex-col items-center justify-center">
                      <span className="text-2xl font-bold font-mono" style={{ color: scoreColor(analysisResult.safetyScore) }}>
                        {analysisResult.safetyScore}
                      </span>
                    </div>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-mono font-bold mb-1" style={{ color: scoreColor(analysisResult.safetyScore) }}>
                      {scoreLabel(analysisResult.safetyScore)}
                    </p>
                    <p className="text-xs leading-relaxed" style={{ color: "#8B949E" }}>
                      {analysisResult.analysis}
                    </p>
                  </div>
                </div>

                {analysisResult.risks.length > 0 && (
                  <div className="space-y-2">
                    <p className="text-[10px] font-mono uppercase tracking-wider" style={{ color: "#6E7681" }}>
                      Risks ({analysisResult.risks.length})
                    </p>
                    {analysisResult.risks.map((risk, i) => (
                      <div
                        key={i}
                        className="rounded p-2.5"
                        style={{ background: "#161B22", border: "1px solid #21262D" }}
                      >
                        <div className="flex items-center gap-2 mb-1.5">
                          <Badge
                            className="text-[9px] font-mono px-1.5 py-0 h-4 shrink-0"
                            style={{
                              background:
                                risk.severity === "critical"
                                  ? "#3C1A1A"
                                  : risk.severity === "high"
                                  ? "#3C1E1A"
                                  : risk.severity === "medium"
                                  ? "#3C2A1A"
                                  : "#1A2A3C",
                              color:
                                risk.severity === "critical"
                                  ? "#F85149"
                                  : risk.severity === "high"
                                  ? "#F0883E"
                                  : risk.severity === "medium"
                                  ? "#D29922"
                                  : "#58A6FF",
                              border: "none",
                            }}
                          >
                            {risk.severity}
                          </Badge>
                          {risk.component && (
                            <span className="text-[10px] font-mono" style={{ color: "#58A6FF" }}>
                              {risk.component}
                            </span>
                          )}
                        </div>
                        <p className="text-xs" style={{ color: "#C9D1D9" }}>
                          {risk.description}
                        </p>
                      </div>
                    ))}
                  </div>
                )}

                {analysisResult.suggestions.length > 0 && (
                  <div className="space-y-2">
                    <p className="text-[10px] font-mono uppercase tracking-wider" style={{ color: "#6E7681" }}>
                      Suggestions
                    </p>
                    <ul className="space-y-1.5">
                      {analysisResult.suggestions.map((s, i) => (
                        <li key={i} className="flex items-start gap-2 text-xs" style={{ color: "#8B949E" }}>
                          <span style={{ color: "#58A6FF" }} className="shrink-0 mt-0.5">→</span>
                          {s}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                <p className="text-[10px] font-mono text-center" style={{ color: "#6E7681" }}>
                  {analysisResult.model}
                </p>
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center gap-3 text-center">
                <ShieldCheck className="w-10 h-10" style={{ color: "#21262D" }} />
                <p className="text-xs font-mono" style={{ color: "#6E7681" }}>
                  Click Analyze Safety to check your circuit for risks, voltage mismatches, and missing protection components.
                </p>
              </div>
            )}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
